# Generated by Django 4.2.7 on 2024-05-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('studID', models.IntegerField(primary_key=True, serialize=False)),
                ('lrn', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=150)),
                ('yearlvl', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('emailadd', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['lastname'],
            },
        ),
        migrations.CreateModel(
            name='RequestedGMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('or_num', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.studentinfo')),
            ],
        ),
    ]
