# Generated by Django 5.0.4 on 2024-05-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0003_remove_schedule_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('equipmentName', models.CharField(max_length=255)),
                ('equipmentSN', models.CharField(max_length=30)),
            ],
        ),
    ]
