# Generated by Django 4.2.11 on 2024-06-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0004_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('donation_type', models.CharField(max_length=10)),
                ('gcash_number', models.CharField(max_length=11)),
                ('paymaya_number', models.CharField(max_length=11)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('address_volunteer', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=11)),
                ('date_sched', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('image_upload', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('image_upload', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
