# Generated by Django 4.2.11 on 2024-05-21 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community_involvement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
